# https://taskfile.dev

version: "3"

vars:
  # GREETING: Hello, World!

tasks:
  # default:
  #   cmds:
  #     - echo "{{.GREETING}}"
  #   silent: true
  test:
    cmds:
      - cd test && go run main.go
    silent: true
